version: '2'

services:

  pma:
    image: phpmyadmin/phpmyadmin
    env_file:
        - .env
    volumes:
      - /sessions
    ports:
      - "${PMA_WEB_PORT}:80"
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: ${MYSQL_HOST}
      PMA_PORT: ${MYSQL_PORT}
    restart: always
    networks:
      - net
  mysql-backup:
    build: ./dockerfiles/mysql-backup-s3
    env_file:
        - .env
    environment:
      MULTI_FILES: "yes"
      MYSQLDUMP_DATABASE: ${BACKUP_DATABASE}
      S3_PREFIX: ${S3_PREFIX}
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_USER: root
      S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID}
      S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}
      S3_BUCKET: ${S3_BUCKET}
      S3_ENDPOINT:  ${S3_ENDPOINT}
      S3_REGION: ${S3_REGION}
      SCHEDULE: "@daily"
    restart: always 
    networks:
      - net

networks:
  net:
    driver: bridge  
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
        

